tenant: "public"
namespace: "default"
name: "debezium-postgres-source"
topicName: "debezium-postgres-topic"
archive: "connectors/pulsar-io-debezium-postgres-3.1.0.nar"
parallelism: 1

configs:

    ## config for pg, docker image: debezium/example-postgress:0.8
    database.hostname: "postgres"
    database.port: "5432"
    database.user: "postgres"
    database.password: "postgres"
    database.dbname: "ecommerce"
    database.server.name: "dbserver1"
    database.whitelist: "ecommerce"
    schema.whitelist: "public"
#    key.converter: "org.apache.kafka.connect.json.JsonConverter"
#    value.converter: "org.apache.kafka.connect.json.JsonConverter"

    ## PULSAR_SERVICE_URL_CONFIG
    pulsar.service.url: "pulsar://127.0.0.1:6650"

# To register the connector run the following source creation command within pulsar broker.
# bin/pulsar-admin source create --source-config-file connectors/debezium-postgres-source-config.yaml