version: '3'
networks:
  pipeline_pulsar:
    external: true
services:
  services:
    container_name: nginx
    image: nginx:latest
    networks:
      - pipeline_pulsar
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
  backend:
    container_name: ecommerce-backend
    networks:
      - pipeline_pulsar
    image: python:3.11.2
    env_file:
      - backend/.env
    ports:
      - 8008:8004
    volumes:
      - ./backend:/app
    command: bash -c "./app/start.sh"
  frontend:
    container_name: ecommerce-frontend
    networks:
      - pipeline_pulsar
    image: node:16.20.0
    ports:
      - 3001:3000
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: bash -c "yarn && yarn start"

