# Generated by Django 4.1.7 on 2023-07-19 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.categories'),
        ),
        migrations.AddField(
            model_name='products',
            name='colors',
            field=models.ManyToManyField(to='inventory.colors'),
        ),
    ]
