# Generated by Django 4.1.7 on 2023-08-14 17:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_products_category_products_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='products',
            name='extra_details',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='products',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, default=''), default=list, size=None),
        ),
        migrations.AddField(
            model_name='products',
            name='pid',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='categories',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('category'), name='categories_category_unique'),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.subcategories'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategories',
            unique_together={('category', 'parent_category')},
        ),
    ]
