# Generated by Django 4.1.7 on 2023-08-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_subcategories_products_actual_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
