# Generated by Django 4.1.7 on 2023-08-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_products_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='products',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
