# Generated by Django 4.1.7 on 2023-09-24 11:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_products_actual_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.subcategories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='colors',
            field=models.ManyToManyField(blank=True, to='inventory.colors'),
        ),
        migrations.AlterField(
            model_name='products',
            name='extra_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='products',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, default=''), blank=True, default=list, size=None),
        ),
    ]
